### ISSUE TITLE
moster.json 잘못 올려서 다시 올립니당

### ISSUE THREAD

**Issue by Z1N00-1015** [hyungseok-choi/SNU_WebProgramming_Final#11]
[
    {
      "id": 1,
      "name": "대학원생",
      "str": 3,
      "def": 2,
      "hp": 3,
      "middleName": ["연구실에서 뛰쳐나온", "퇴근을 모르는", "3일째 집에 못간", "체크남방", "주말에 출근하는"]
    },
    {
      "id": 2,
      "name": "교수님",
      "str": 3,
      "def": 2,
      "hp": 3,
      "middleName": ["정년퇴임을 앞둔",	"종강을 모르는", "학과장", "폴리페서", "내 이름을 기억하는"]
    },
    {
      "id": 3,
      "name": "전도하는 사람",
      "str": 3,
      "def": 2,
      "hp": 3,
      "middleName": ["강의실까지 쫓아와서", "신앙심이 매우 깊은", "호시탐탐 기회를 옅보는", "말끔하게 차려입은", "교수님인척 하는"]
    },
    {
      "id": 4,
      "name": "전 여친",
      "str": 3,
      "def": 2,
      "hp": 3,
      "middleName": ["과CC 였던", "바람펴서 헤어진", "같은 수업을 듣는", "핵인싸", "다른 남자와 걸어가는"]
    },
    {
      "id": 5,
      "name": "등산객",
      "str": 3,
      "def": 2,
      "hp": 3,
      "middleName": ["막걸리를 마신", "바지 한쪽을 걷어 올린", "새벽부터 산을 타는", "술병을 들고 가는", "술에 취한"]
    },
    {
      "id": 6,
      "name": "엄준식",
      "str": 3,
      "def": 2,
      "hp": 3,
      "middleName": ["한국 남자", "관악구 맘카페 정회원", "노약자석 절대강자", "공무원 시험 합격은", "군필 여고생"]
    }
  ]
  

어떻게 main으로 얘만 push할 수 있는지 몰라서 이렇게 올릴게용 8ㅅ8

**Comment by hyungseok-choi** [comment]
반영해서 main에 merge했습니다!
