### ISSUE TITLE
게임화면 구성 방안 의견

### ISSUE THREAD

**Issue by hyungseok-choi** [hyungseok-choi/SNU_WebProgramming_Final#3]
현재 화면 구성 제안

══════════ Player ══════════
ID: { 아이디 }
Lv. { 레벨 } / EXP. { 경험치 }
str. { 힘 } / def. { 방어력 } / HP. { [ /////   ] }

══════════ Map ══════════

{ 맵 설명 }
{이동버튼}, {이동버튼}
{전투중 버튼}

════════ Inventory ══════════

╔═══════════╗
║  1. {아이템 명}     ║
║  { 아이템 효과 }   ║
╚═══════════╝
╔═══════════╗
║  2. {아이템 명}     ║
║  { 아이템 효과 }   ║
╚═══════════╝
╔═══════════╗
║  3. {아이템 명}     ║
║  { 아이템 효과 }   ║
╚═══════════╝

이런식으로 하면 너무 무리일까요ㅎㅎㅎ

**Comment by mskang4171** [comment]
되게 깔끔하고 좋은 것 같습니다! 좀 게임스러워져서 몰입도가 높을 것 같아요
그런데 게임의 메인 화면인 Map이 가장 위에 있는게 좋지 않을까요?
Player랑 Inventory는 참고 느낌으로요!

**Comment by hyungseok-choi** [comment]
넵 피드백 감사드립니다ㅎㅎ
코드먼저 돌아가게 하고서 ejs 파일 수정하는 방향으로 해보아요!

**Comment by mskang4171** [comment]
넵 형석님 화이팅입니다
내일 모레 중으로 다시 회의해봅시다!

**Comment by Z1N00-1015** [comment]
앗 깃허브 쓰는법이 익숙하지 않아서 지금 봤네요 죄송합니다 ㅠㅠ
저도 민수님 말씀처럼 맵이 맨 위에 있는게 좋을 것 같습니다!
텍스트로 보는 나름의 맛이 있네용ㅋㅋ,,
